#!/bin/bash

echo "=== Running DRM Application on TTY ==="
echo ""
echo "To see the framebuffer output, you need to switch to a TTY (text terminal)"
echo "where X11/Wayland is not running."
echo ""
echo "Instructions:"
echo "1. Press Ctrl+Alt+F3 (or F4, F5, F6) to switch to a TTY"
echo "2. Log in with your username and password"
echo "3. Navigate to this directory:"
echo "   cd $(pwd)"
echo "4. Run the application:"
echo "   sudo ./test_drm.sh"
echo ""
echo "The rendered frames should appear directly on the screen!"
echo ""
echo "To return to your desktop:"
echo "- Press Ctrl+Alt+F1 or Ctrl+Alt+F7 (depending on your system)"
echo ""
echo "Note: You need sudo because framebuffer access typically requires root privileges."
